Traceback (most recent call last):
  File "/home/bilalelysium/repositories/elysium/passenger_wsgi.py", line 3, in <module>
    from elysium.wsgi import application
  File "/home/bilalelysium/repositories/elysium/elysium/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "/home/bilalelysium/repositories/elysium/passenger_wsgi.py", line 3, in <module>
    from elysium.wsgi import application
  File "/home/bilalelysium/repositories/elysium/elysium/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Not Found: /static/admin/css/base.css
Not Found: /static/admin/css/nav_sidebar.css
Not Found: /static/admin/css/login.css
Not Found: /static/admin/css/responsive.css
Not Found: /static/admin/js/nav_sidebar.js
Not Found: /static/admin/css/base.css
Not Found: /static/admin/css/nav_sidebar.css
Not Found: /static/admin/css/dashboard.css
Not Found: /static/admin/css/responsive.css
Not Found: /static/admin/js/nav_sidebar.js
Not Found: /static/admin/css/base.css
Not Found: /static/admin/css/nav_sidebar.css
Not Found: /static/admin/css/responsive.css
Not Found: /static/admin/js/nav_sidebar.js
Not Found: /static/admin/css/dashboard.css
Not Found: /static/admin/css/base.css
Not Found: /static/admin/css/responsive.css
Not Found: /static/admin/css/dashboard.css
Not Found: /static/admin/js/nav_sidebar.js
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/templatetags/static.py", line 106, in render
    url = self.url(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/templatetags/static.py", line 103, in url
    return self.handle_simple(path)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/templatetags/static.py", line 118, in handle_simple
    return staticfiles_storage.url(path)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/utils/functional.py", line 246, in inner
    self._setup()
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 438, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/whitenoise/storage.py", line 131, in __init__
    super().__init__(*args, **kwargs)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 373, in __init__
    self.hashed_files = self.load_manifest()
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 383, in load_manifest
    content = self.read_manifest()
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 377, in read_manifest
    with self.open(self.manifest_name) as manifest:
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/core/files/storage.py", line 38, in open
    return self._open(name, mode)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/core/files/storage.py", line 243, in _open
    return File(open(self.path(name), mode))
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 38, in path
    raise ImproperlyConfigured("You're using the staticfiles app "
django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/templatetags/static.py", line 106, in render
    url = self.url(context)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/templatetags/static.py", line 103, in url
    return self.handle_simple(path)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/templatetags/static.py", line 118, in handle_simple
    return staticfiles_storage.url(path)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/utils/functional.py", line 246, in inner
    self._setup()
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 438, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/whitenoise/storage.py", line 131, in __init__
    super().__init__(*args, **kwargs)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 373, in __init__
    self.hashed_files = self.load_manifest()
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 383, in load_manifest
    content = self.read_manifest()
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 377, in read_manifest
    with self.open(self.manifest_name) as manifest:
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/core/files/storage.py", line 38, in open
    return self._open(name, mode)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/core/files/storage.py", line 243, in _open
    return File(open(self.path(name), mode))
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 38, in path
    raise ImproperlyConfigured("You're using the staticfiles app "
django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /robots.txt
Not Found: /sitemap.xml
Not Found: /wp-admin/admin-ajax.php
Not Found: /favicon.ico
/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1416: RuntimeWarning: DateTimeField Attendance.attendance_time received a naive datetime (2022-07-14 21:18:00.857235) while time zone support is active.
  warnings.warn("DateTimeField %s received a naive datetime (%s)"
Internal Server Error: /api/attendance/add/
Traceback (most recent call last):
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/bilalelysium/repositories/elysium/core/views.py", line 95, in add
    member = Profile.objects.get(id=user_id)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
core.models.Profile.DoesNotExist: Profile matching query does not exist.
/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1416: RuntimeWarning: DateTimeField Attendance.attendance_time received a naive datetime (2022-07-14 21:18:24.875118) while time zone support is active.
  warnings.warn("DateTimeField %s received a naive datetime (%s)"
Internal Server Error: /api/attendance/add/
Traceback (most recent call last):
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1823, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'pp'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/bilalelysium/repositories/elysium/core/views.py", line 95, in add
    member = Profile.objects.get(id=user_id)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 424, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1416, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1435, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1370, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1216, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/db/models/lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/db/models/lookups.py", line 77, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1825, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'pp'.
/home/bilalelysium/virtualenv/repositories/elysium/3.8/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1416: RuntimeWarning: DateTimeField Attendance.attendance_time received a naive datetime (2022-07-14 21:18:34.443055) while time zone support is active.
  warnings.warn("DateTimeField %s received a naive datetime (%s)"
